### ISSUE TITLE
隐藏el-table-infinite-scroll组件时，出现以下error:Error in directive el-table-infinite-scroll unbind hook: "TypeError: Cannot read property 'container' of undefined

### ISSUE THREAD

**Issue by wulilele** [sad-xu/vue-template#1]
Error in directive el-table-infinite-scroll unbind hook: "TypeError: Cannot read property 'container' of undefined

**Comment by chxve** [comment]
感谢指出bug。没开通知，直到今天才看见多了个issue😅
原因是组件销毁时，`unbind` 钩子解绑的节点不对
